language: java
jdk:
  - oraclejdk8
  
script: ./travis.sh
  
addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
    -  $(ls ./target/*.jar | tr "\n" ":")
    target_paths: builds/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER
after_success:
  - mvn clean test jacoco:report coveralls:report 
